#include <iostream>
#include <iomanip>
// Generated by verilator
#include "verilated.h"
#include "Vpacket_parser.h" 

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    
    //  Instantiate the hardware module 
    Vpacket_parser* dut = new Vpacket_parser;

    // Initialize inputs to 0
    dut->clk = 0;
    dut->rst_n = 0; // Assert reset (active low)
    dut->s_axis_tvalid = 0;
    dut->s_axis_tdata = 0;
    dut->s_axis_tlast = 0;

    // Toggle the clock to apply the reset to the DFFs
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();

    // Release reset so the module can run
    dut->rst_n = 1;
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();

    // A fake 42-byte UDP packet
    std::uint8_t fake_packet[42] = {
        // Bytes 0-11: MAC Addresses (Dummy data)
        0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB,
        // Bytes 12-13: EtherType (IPv4 -> 0x0800)
        0x08, 0x00,
        // Bytes 14-22: IPv4 header start (Dummy data)
        0x45, 0x00, 0x00, 0x2E, 0x00, 0x00, 0x00, 0x00, 0x40, 
        // Byte 23: Protocol (UDP -> 0x11)
        0x11, 
        // Bytes 24-25: Checksum (Dummy)
        0x00, 0x00,
        // Bytes 26-29: Source IP (192.168.1.50 -> C0 A8 01 32)
        0xC0, 0xA8, 0x01, 0x32,
        // Bytes 30-33: Dest IP (10.0.0.1 -> 0A 00 00 01)
        0x0A, 0x00, 0x00, 0x01,
        // Bytes 34-35: Source Port (1234 -> 04 D2)
        0x04, 0xD2,
        // Bytes 36-37: Dest Port (80 -> 00 50)
        0x00, 0x50,
        // Bytes 38-41: UDP Length/Checksum (Dummy)
        0x00, 0x00, 0x00, 0x00
    };

    std::cout << "Starting packet injection...\n";

    for (std::size_t i{}; i < 42; ++i)
    {
        dut->s_axis_tdata = fake_packet[i];
        dut->s_axis_tvalid = 1;
        dut->s_axis_tlast = (i == 41) ? 1 : 0;
        dut->clk = 1; dut->eval();
        dut->clk = 0; dut->eval();

        if (dut->parsed_valid) 
        {
            std::cout << std::hex 
                      << "Source IP:        0x" << dut->parsed_src_ip << "\n"
                      << "Destination IP:   0x" << dut->parsed_dst_ip << "\n"
                      << "Source Port:      0x" << dut->parsed_src_port << "\n"
                      << "Destination Port: 0x" << dut->parsed_dst_port << "\n";
        }
    }

    // Cleanup
    delete dut;
    return 0;
}