#include <iostream>
#include <iomanip>
#include <vector>
#include <string_view>
#include <verilated_vcd_c.h>
#include <fstream>
#include <cassert>
// Generated by Verilator from pipeline_top.sv
#include "Vpipeline_top.h" 
#include "verilated.h"

// PCAP Global Header (24 bytes)
struct pcap_global_header {
    uint32_t magic_number;   
    uint16_t version_major;  
    uint16_t version_minor;  
    int32_t  thiszone;       
    uint32_t sigfigs;        
    uint32_t snaplen;        
    uint32_t network;        
};

// PCAP Packet Header (16 bytes)
struct pcap_packet_header {
    uint32_t ts_sec;         
    uint32_t ts_usec;        
    uint32_t incl_len;       // Number of bytes saved in file
    uint32_t orig_len;       // Actual length of packet
};

// Software Reference Model
bool software_reference_model(const std::vector<uint8_t>& packet) {
    // Standard Ethernet header is 14 bytes. IPv4 Source IP starts at byte 26.
    if (packet.size() < 30) return false; 
    
    // Reconstruct the 32-bit Source IP from the 4 byte vector elements
    uint32_t src_ip = (packet[26] << 24) | (packet[27] << 16) | 
                      (packet[28] << 8)  | packet[29];
                      
    // Define the exact same blocklist as the hardware rule_table
    std::vector<uint32_t> blocklist = {
        0xFFFFFFFF, // 255.255.255.255
        0xC0A80164, // 192.168.1.100
        0x0A000005  // 10.0.0.5
    };
    
    // Check if the source IP exists in our blocklist
    for (uint32_t blocked_ip : blocklist) {
        if (src_ip == blocked_ip) {
            return true; // Drop
        }
    }
    
    return false; // Pass
}

// Reusable function to inject a packet and monitor the outputs
void inject_packet(Vpipeline_top* dut, const std::vector<uint8_t>& packet, std::string_view name, VerilatedVcdC* tfp, uint64_t& sim_time) {
    std::cout << "\nInjecting " << name << "...\n";

    bool expected_drop = software_reference_model(packet);
    
    std::size_t i = 0;
    while (i < packet.size()) {
        // Drive data and valid
        dut->s_axis_tdata = packet[i];
        dut->s_axis_tvalid = 1;
        dut->s_axis_tlast = (i == packet.size() - 1) ? 1 : 0;

        // AXI Handshake check: Did the hardware accept the byte on this rising edge?
        bool accepted = (dut->s_axis_tready == 1);
        
        // Toggle clock high
        dut->clk = 1; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        // Toggle clock low
        dut->clk = 0; dut->eval();
        if (tfp) tfp->dump(sim_time++);

        if (dut->classify_valid) {
            bool actual_drop = (dut->action_drop == 1);
            std::cout << "Hardware Drop: " << actual_drop 
                      << " | Software Expected: " << expected_drop << "\n";
            assert(actual_drop == expected_drop && "Mismatch: Hardware dropped incorrectly!");
        }
        
        // Only move to the next byte if the hardware was ready
        if (accepted) {
            i++;
        }
    }
    
    // Add idle clock cycles to let the pipeline process the final bytes and scan the memory
    dut->s_axis_tvalid = 0;
    dut->s_axis_tlast = 0;
    for (int j = 0; j < 10; ++j) { // 10 cycles gives plenty of time to scan the table
        dut->clk = 1; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        dut->clk = 0; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        // Check for the classification result during the pipeline drain
        if (dut->classify_valid) {
            std::cout << "Classification Result -> action_drop: " 
                      << static_cast<int>(dut->action_drop) << "\n";
        }
    }
    
    // Add a few idle clock cycles between packets
    dut->s_axis_tvalid = 0;
    for (int i = 0; i < 5; ++i) {
        dut->clk = 1; dut->eval();
        dut->clk = 0; dut->eval();
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    
    // Instantiate top-level module
    Vpipeline_top* dut = new Vpipeline_top;

    // Enable tracing
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;
    dut->trace(tfp, 99);  // Trace 99 levels of module hierarchy, this is arbitrarily deep
    tfp->open("sim/waveform.vcd"); 

    // Initialize inputs
    dut->clk = 0;
    dut->rst_n = 0; 
    dut->s_axis_tvalid = 0;
    dut->s_axis_tdata = 0;
    dut->s_axis_tlast = 0;

    // Timeline
    std::uint64_t sim_time = 0;

    // Reset sequence
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();
    dut->rst_n = 1;
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();

    uint64_t total_bytes = 0;

    // Open the PCAP file in binary mode
    std::ifstream pcap_file("sim/test_traffic.pcap", std::ios::binary);
    if (!pcap_file.is_open()) {
        std::cerr << "Error: Could not open sim/test_traffic.pcap\n";
        return 1;
    }

    // Read and discard the global header (just need to move the file pointer past it)
    pcap_global_header global_hdr;
    pcap_file.read(reinterpret_cast<char*>(&global_hdr), sizeof(global_hdr));

    // Loop through the file, reading each packet one by one
    pcap_packet_header pkt_hdr;
    int packet_number = 1;
    
    while (pcap_file.read(reinterpret_cast<char*>(&pkt_hdr), sizeof(pkt_hdr))) {
        // Create a vector sized exactly to the packet's captured length
        std::vector<uint8_t> packet_data(pkt_hdr.incl_len);

        total_bytes += pkt_hdr.incl_len;
        
        // Read the raw packet bytes directly into the vector
        pcap_file.read(reinterpret_cast<char*>(packet_data.data()), pkt_hdr.incl_len);
        
        // Generate a dynamic name for the terminal output
        std::string pkt_name = "PCAP Packet " + std::to_string(packet_number++);
        
        // Inject the packet into the hardware simulation
        inject_packet(dut, packet_data, pkt_name, tfp, sim_time);
    }
    
    // Final Performance Metrics from Hardware Counters
    std::cout << "\n============================================\n";
    std::cout << "--- Pipeline Performance Metrics ---\n";
    std::cout << "Total Clock Cycles:      " << dut->cycle_count << "\n";
    std::cout << "Total Packets Processed: " << dut->packet_count << "\n";
    std::cout << "Total Bytes Injected:    " << total_bytes << "\n";

    if (dut->packet_count > 0) {
        // Latency: Average cycles per packet
        double latency = static_cast<double>(dut->cycle_count) / dut->packet_count;
        
        // Throughput: (Bits Processed) / (Total Time)
        // Assuming a target 250 MHz clock frequency (4.0 ns period)
        double total_time_ns = dut->cycle_count * 4.0; 
        double throughput_gbps = (total_bytes * 8.0) / total_time_ns;

        std::cout << "Average Latency:         " << latency << " cycles/packet\n";
        std::cout << "Sustained Throughput:    " << throughput_gbps << " Gbps (@ 250 MHz)\n";
    }
    std::cout << "============================================\n";

    // Cleanup
    pcap_file.close();
    tfp->close();
    delete tfp;
    delete dut;
    return 0;
}