#include <iostream>
#include <iomanip>
#include <vector>
#include <string_view>
#include <verilated_vcd_c.h>
// Generated by Verilator from pipeline_top.sv
#include "Vpipeline_top.h" 
#include "verilated.h"

// Reusable function to inject a packet and monitor the outputs
void inject_packet(Vpipeline_top* dut, const std::vector<uint8_t>& packet, std::string_view name, VerilatedVcdC* tfp, uint64_t& sim_time) {
    std::cout << "\nInjecting " << name << "...\n";
    
    std::size_t i = 0;
    while (i < packet.size()) {
        // Drive data and valid
        dut->s_axis_tdata = packet[i];
        dut->s_axis_tvalid = 1;
        dut->s_axis_tlast = (i == packet.size() - 1) ? 1 : 0;

        // AXI Handshake check: Did the hardware accept the byte on this rising edge?
        bool accepted = (dut->s_axis_tready == 1);
        
        // Toggle clock high
        dut->clk = 1; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        // Toggle clock low
        dut->clk = 0; dut->eval();
        if (tfp) tfp->dump(sim_time++);

        // Check if the classifier has evaluated this packet early
        if (dut->classify_valid) {
            std::cout << "Classification Result -> action_drop: " 
                      << static_cast<int>(dut->action_drop) << "\n";
        }
        
        // Only move to the next byte if the hardware was ready
        if (accepted) {
            i++;
        }
    }
    
    // Add idle clock cycles to let the pipeline process the final bytes and scan the memory
    dut->s_axis_tvalid = 0;
    dut->s_axis_tlast = 0;
    for (int j = 0; j < 10; ++j) { // 10 cycles gives plenty of time to scan the table
        dut->clk = 1; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        dut->clk = 0; dut->eval();
        if (tfp) tfp->dump(sim_time++);
        
        // Check for the classification result during the pipeline drain
        if (dut->classify_valid) {
            std::cout << "Classification Result -> action_drop: " 
                      << static_cast<int>(dut->action_drop) << "\n";
        }
    }
    
    // Add a few idle clock cycles between packets
    dut->s_axis_tvalid = 0;
    for (int i = 0; i < 5; ++i) {
        dut->clk = 1; dut->eval();
        dut->clk = 0; dut->eval();
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    
    // Instantiate top-level module
    Vpipeline_top* dut = new Vpipeline_top;

    // Enable tracing
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;
    dut->trace(tfp, 99);  // Trace 99 levels of module hierarchy, this is arbitrarily deep
    tfp->open("sim/waveform.vcd"); 

    // Initialize inputs
    dut->clk = 0;
    dut->rst_n = 0; 
    dut->s_axis_tvalid = 0;
    dut->s_axis_tdata = 0;
    dut->s_axis_tlast = 0;

    // Timeline
    std::uint64_t sim_time = 0;

    // Reset sequence
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();
    dut->rst_n = 1;
    dut->clk = 1; dut->eval();
    dut->clk = 0; dut->eval();

    // Benign Packet (Source IP: 192.168.1.50 -> C0 A8 01 32)
    std::vector<uint8_t> benign_packet = {
        0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB,
        0x08, 0x00, 0x45, 0x00, 0x00, 0x2E, 0x00, 0x00, 0x00, 0x00, 0x40, 0x11, 
        0x00, 0x00, 
        0xC0, 0xA8, 0x01, 0x32, // Source IP: 192.168.1.50
        0x0A, 0x00, 0x00, 0x01, 0x04, 0xD2, 0x00, 0x50, 0x00, 0x00, 0x00, 0x00
    };

    // Malicious Packet (Source IP: 192.168.1.100 -> C0 A8 01 64)
    std::vector<uint8_t> malicious_packet = benign_packet;
    malicious_packet[29] = 0x64; // Overwrite the last byte of the Source IP to 100

    // Run the simulation
    inject_packet(dut, benign_packet, "Benign Packet (192.168.1.50)", tfp, sim_time);
    inject_packet(dut, malicious_packet, "Malicious Packet (192.168.1.100)", tfp, sim_time);

    // Cleanup
    tfp->close();
    delete tfp;
    delete dut;
    return 0;
}